baseURL = 'devblog.ayushb.com'
languageCode = 'en-us'
title = 'DevBlog Theme Demo Site'
theme = 'devblog'

[params]
  description = "This is a demo site for the hugo DevBlog Theme"
  favicon = "/favicon.ico"

[params.social]
  github = "aaxyat"
  twitter = "aaxyat"
  linkedin = "mrbhattarai"

[params.hero]
  style = "default"
  title = "Welcome to DevBlog"
  description = "Exploring the world of technology through a developer's eyes."
  backgroundImage = "https://farm5.staticflickr.com/4900/31876584947_5eca9e7362_o.jpg?fdl=1"

  [[params.hero.customLinks]]
    name = "Documentation"
    url = "https://github.com/aaxyat/hugo-devblog/blob/main/wiki.md"
    icon = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z\"></path><path d=\"M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z\"></path></svg>"
    class = "outline"
    target = "_blank"

[params.footer]
  aboutTitle = "About DevBlog"  # Default: "About [site.Title]"
  aboutContent = "A custom about text for the footer that can be different from the site description."
  
  # Add buttons below about text (optional)
  [[params.footer.aboutButtons]]
    name = "Contact"
    url = "/contact"
    icon = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z\"></path></svg>"
  
  [[params.footer.aboutButtons]]
    name = "Subscribe"
    url = "#newsletter"
    class = "primary"

